routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'auth.admin']], function($router){
    $router->get('/', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    $router->resource('categories', 'CategoriesController', ['except' => ['show']]);
    $router->resource('providers', 'ProvidersController', ['except' => ['show']]);
    $router->resource('products', 'ProductsController', ['except' => ['show']]);
});

app/Models/Product.php
<?php

namespace App\Models;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes, Sluggable;
    protected $guarded = ['id'];

    public function category()
    {
        return $this->belongsTo('App\Models\Category');
    }

    public function providers()
    {
        return $this->belongsToMany('App\Models\Provider', 'product_provider');
    }

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Models\Product;
use App\Models\Provider;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = "Products";
        $products = Product::with('category')->orderBy('id', 'DESC')->get();
        return view('admin.products.index', compact('title', 'products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('name')->pluck('name', 'id')->toArray();
        $providers = Provider::orderBy('name')->get();
        $title = "New Product";
        return view('admin.products.create', compact('title', 'providers', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $title }}</div>
                    <div class="panel-body">
                        @if(count($errors) > 0)
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <p>{{ $error }}</p>
                                @endforeach
                            </div>
                        @endif
                        {{ Form::open(['route' => 'products.store']) }}
                        <div class="form-group">
                            <label for="">Name</label>
                            {{ Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => 'Provider Name']) }}
                        </div>
                        <div class="form-group">
                            <label for="">SKU</label>
                            {{ Form::text('sku', old('sku'), ['class' => 'form-control', 'placeholder' => 'SKU']) }}
                        </div>
                        <div class="form-group">
                            <label for="">Description</label>
                            {{ Form::textarea('description', old('description'), ['class' => 'form-control', 'placeholder' => 'Description', 'rows' => 4]) }}
                        </div>
                        <div class="form-group">
                            <label for="">Category</label>
                            {{ Form::select('category_id', $categories, old('category_id'), ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Save', ['class' => 'btn btn-primary']) }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $title }}</div>
                    <div class="panel-body">
                        @if(count($errors) > 0)
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    <p>{{ $error }}</p>
                                @endforeach
                            </div>
                        @endif
                        {{ Form::open(['route' => 'products.store']) }}
                        <div class="form-group">
                            <label for="">Name</label>
                            {{ Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => 'Provider Name']) }}
                        </div>
                        <div class="form-group">
                            <label for="">SKU</label>
                            {{ Form::text('sku', old('sku'), ['class' => 'form-control', 'placeholder' => 'SKU']) }}
                        </div>
                        <div class="form-group">
                            <label for="">Description</label>
                            {{ Form::textarea('description', old('description'), ['class' => 'form-control', 'placeholder' => 'Description', 'rows' => 4]) }}
                        </div>
                        <div class="form-group">
                            <label for="">Category</label>
                            {{ Form::select('category_id', $categories, old('category_id'), ['class' => 'form-control']) }}
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="instock" {{ ($product->instock) ? 'checked' : '' }}> InStock
                            </label>
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Save', ['class' => 'btn btn-primary']) }}
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $title }}</div>
                    <div class="panel-body">
                        <div class="form-group">
                            <a href="{{ route('products.create') }}" class="btn btn-primary">New Product</a>
                        </div>
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>SKU</th>
                                <th>Category</th>
                                <th>inStock</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($products as $p)
                                <tr>
                                    <td>{{ $p->id }}</td>
                                    <td>{{ $p->name }}</td>
                                    <td>{{ $p->sku }}</td>
                                    <td>{{ $p->category->name }}</td>
                                    <td>
                                        @if($p->instock)
                                            <span class="btn btn-xs btn-success">Yes</span>
                                        @else
                                            <span class="btn btn-xs btn-danger">No</span>
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{ route('products.edit', $p->id) }}" class="btn btn-default btn-xs">Edit</a>
                                        {{ Form::open(['route' => ['products.destroy', $p->id], 'class' => 'form-delete', 'method' => 'DELETE']) }}
                                        <button class="btn btn-xs btn-danger">Delete</button>
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop


@section('scripts')
    <script>
        $(function(){
            $('.form-delete').submit(function(e){
                if(!confirm('Are you sure to delete this item?')){
                    e.preventDefault();
                }
            });
        })
    </script>
@stop